spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
    proxy-target-class: true
  redis:
    host: 10.11.23.14
    port: 10037
    database: 0
    password:
    timeout: 1000
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.238.128:9300
  application:
    name: elasticSearch
  profiles:
    active: dev
    default: dev


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.rickiyang.learn.entity
  configLocation: classpath:mybatis-config.xml



server:
  port: 9955

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /