regCenter:
  serverList: localhost:2181 #注册中心 zk的 修改自己IP
  namespace: test # 命名空间 修改自己的
simpleJob:
  cron: 0/1 * * * * ? #定时规则
  shardingTotalCount: 2 #分片数
  shardingItemParameters: 0=A,1=B #分片策略
  cron1: 0/1 * * * * ? #定时规则
  shardingTotalCount1: 3 #分片数
  shardingItemParameters1: 0=A,1=B,2=C #分片策略


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver