spring:
  application:
    name: springboot-dubbo
server:
  port: 9091


dubbo:
  application:
    name: member
  protocol:
    name: dubbo
    port: 20881
    serialization: json
  registry:
    address: zookeeper://192.168.50.128:2181
  scan:
    base-packages: com.rickiyang.learn.service.impl



    spring.dubbo.protocol.name=dubbo
    spring.dubbo.protocol.serialization=hessian2

    spring.dubbo.consumer.retries=0
    spring.dubbo.consumer.timeout=1000
    spring.dubbo.consumer.check=false